name: my-jnb
dependencies:
  - python=3.6.6
  - keras=2.2.0
  - requests=2.19.1
  - matplotlib=2.2.2
  - pip:
    - tensorflow==1.9.0
    - scikit-learn==0.19.2
    - Pillow==5.2.0
    - scipy==1.1.0
    - opencv-python==3.4.0.12
